### ISSUE TITLE
**Incomplete

### ISSUE THREAD

**Issue by tanelam** [sthlmj/bwa-u4-feature-request#1]
Please push up the files for this project. Here is a [cheat sheet](https://www.git-tower.com/blog/git-cheat-sheet) to learn more on how to push up a project in GitHub.

**Comment by sthlmj** [comment]
@tanelam Hi, I've submitted the project folder now. Submitted only technical design for unit 4 since I thought it was optional to implement the feature. Here is the repo that I re-submitted: https://github.com/sthlmj/jammming and within the public folder is the technical design documentation. https://github.com/sthlmj/jammming/blob/master/public/codecademy%20jammming%20Feature%20Request%20Template.txt
